// Complete pages configuration for NPS Portal
// Maps all 131 pages with routes, roles, and navigation groups

export const pagesConfig = {
  // Admin Dashboard Pages
  adminDashboard: {
    name: 'AdminDashboard',
    path: '/AdminDashboard',
    roles: ['super_admin', 'admin'],
    group: 'Dashboard',
    label: 'Admin Dashboard',
  },
  adminMore: {
    name: 'AdminMore',
    path: '/AdminMore',
    roles: ['super_admin', 'admin'],
    group: 'Dashboard',
    label: 'More',
  },
  adminAnalyticsDashboard: {
    name: 'AdminAnalyticsDashboard',
    path: '/AdminAnalyticsDashboard',
    roles: ['super_admin', 'admin'],
    group: 'Analytics',
    label: 'Analytics Dashboard',
  },
  analyticsDashboard: {
    name: 'AnalyticsDashboard',
    path: '/AnalyticsDashboard',
    roles: ['super_admin', 'admin'],
    group: 'Analytics',
    label: 'Employee Analytics',
  },

  // Supervisor Pages
  supervisorDashboard: {
    name: 'SupervisorDashboard',
    path: '/SupervisorDashboard',
    roles: ['super_admin', 'supervisor'],
    group: 'Dashboard',
    label: 'Supervisor Dashboard',
  },
  supervisorMore: {
    name: 'SupervisorMore',
    path: '/SupervisorMore',
    roles: ['super_admin', 'supervisor'],
    group: 'Dashboard',
    label: 'More',
  },

  // Employee/Officer Pages
  employeeHome: {
    name: 'EmployeeHome',
    path: '/EmployeeHome',
    roles: ['super_admin', 'employee'],
    group: 'Dashboard',
    label: 'Home',
  },
  officerDashboard: {
    name: 'OfficerDashboard',
    path: '/OfficerDashboard',
    roles: ['super_admin', 'officer'],
    group: 'Dashboard',
    label: 'Officer Dashboard',
  },
  employeeMore: {
    name: 'EmployeeMore',
    path: '/EmployeeMore',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Dashboard',
    label: 'More',
  },

  // Client Pages
  clientPortal: {
    name: 'ClientPortal',
    path: '/ClientPortal',
    roles: ['super_admin', 'client'],
    group: 'Dashboard',
    label: 'Portal',
  },
  clientSecureDashboard: {
    name: 'ClientSecureDashboard',
    path: '/ClientSecureDashboard',
    roles: ['super_admin', 'client'],
    group: 'Dashboard',
    label: 'Secure Dashboard',
  },
  clientMore: {
    name: 'ClientMore',
    path: '/ClientMore',
    roles: ['super_admin', 'client'],
    group: 'Dashboard',
    label: 'More',
  },

  // Employee Management
  employeeDirectory: {
    name: 'EmployeeDirectory',
    path: '/EmployeeDirectory',
    roles: ['super_admin', 'admin', 'supervisor', 'manager'],
    group: 'People',
    label: 'Employee Directory',
  },
  newEmployee: {
    name: 'NewEmployee',
    path: '/NewEmployee',
    roles: ['super_admin', 'admin'],
    group: 'People',
    label: 'Add Employee',
  },
  employeeProfile: {
    name: 'EmployeeProfile',
    path: '/EmployeeProfile',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'People',
    label: 'Employee Profile',
  },
  userManagement: {
    name: 'UserManagement',
    path: '/UserManagement',
    roles: ['super_admin', 'admin'],
    group: 'People',
    label: 'User Management',
  },
  inviteUser: {
    name: 'InviteUser',
    path: '/InviteUser',
    roles: ['super_admin', 'admin'],
    group: 'People',
    label: 'Invite User',
  },
  pendingInvites: {
    name: 'PendingInvites',
    path: '/PendingInvites',
    roles: ['super_admin', 'admin'],
    group: 'People',
    label: 'Pending Invites',
  },
  profilePhotoApproval: {
    name: 'ProfilePhotoApproval',
    path: '/ProfilePhotoApproval',
    roles: ['super_admin', 'admin'],
    group: 'People',
    label: 'Photo Approvals',
  },
  bulkEmployeeActions: {
    name: 'BulkEmployeeActions',
    path: '/BulkEmployeeActions',
    roles: ['super_admin', 'admin'],
    group: 'People',
    label: 'Bulk Actions',
  },
  positionManagement: {
    name: 'PositionManagement',
    path: '/PositionManagement',
    roles: ['super_admin', 'admin'],
    group: 'People',
    label: 'Positions',
  },

  // Scheduling & Timekeeping
  scheduling: {
    name: 'Scheduling',
    path: '/Scheduling',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'Operations',
    label: 'Scheduling',
  },
  schedule: {
    name: 'Schedule',
    path: '/Schedule',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer', 'client'],
    group: 'Operations',
    label: 'Schedule',
  },
  timesheet: {
    name: 'Timesheet',
    path: '/Timesheet',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'Operations',
    label: 'Timesheet',
  },
  timesheetsManagement: {
    name: 'TimesheetsManagement',
    path: '/TimesheetsManagement',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Operations',
    label: 'Timesheet Management',
  },
  ptoRequest: {
    name: 'PTORequest',
    path: '/PTORequest',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Operations',
    label: 'PTO Request',
  },
  ptoApproval: {
    name: 'PTOApproval',
    path: '/PTOApproval',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Operations',
    label: 'PTO Approval',
  },
  ptoCalendar: {
    name: 'PTOCalendar',
    path: '/PTOCalendar',
    roles: ['super_admin', 'admin'],
    group: 'Operations',
    label: 'PTO Calendar',
  },
  ptoSettings: {
    name: 'PTOSettings',
    path: '/PTOSettings',
    roles: ['super_admin', 'admin'],
    group: 'Settings',
    label: 'PTO Settings',
  },
  shiftBidding: {
    name: 'ShiftBidding',
    path: '/ShiftBidding',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Operations',
    label: 'Shift Bidding',
  },

  // Patrol & Operations
  patrol: {
    name: 'Patrol',
    path: '/Patrol',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Operations',
    label: 'Patrol',
  },
  liveMap: {
    name: 'LiveMap',
    path: '/LiveMap',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Operations',
    label: 'Live Map',
  },
  patrolReview: {
    name: 'PatrolReview',
    path: '/PatrolReview',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Operations',
    label: 'Patrol Review',
  },
  patrolPlayback: {
    name: 'PatrolPlayback',
    path: '/PatrolPlayback',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Operations',
    label: 'Patrol Playback',
  },
  patrolHistory: {
    name: 'PatrolHistory',
    path: '/PatrolHistory',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Operations',
    label: 'Patrol History',
  },
  patrolAnalytics: {
    name: 'PatrolAnalytics',
    path: '/PatrolAnalytics',
    roles: ['super_admin', 'admin'],
    group: 'Analytics',
    label: 'Patrol Analytics',
  },
  officerAnalytics: {
    name: 'OfficerAnalytics',
    path: '/OfficerAnalytics',
    roles: ['super_admin', 'admin'],
    group: 'Analytics',
    label: 'Officer Analytics',
  },
  gpsViolations: {
    name: 'GPSViolations',
    path: '/GPSViolations',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Operations',
    label: 'GPS Violations',
  },
  deletedPatrolsReport: {
    name: 'DeletedPatrolsReport',
    path: '/DeletedPatrolsReport',
    roles: ['super_admin', 'admin'],
    group: 'Operations',
    label: 'Deleted Patrols',
  },

  // Site Management
  siteManagement: {
    name: 'SiteManagement',
    path: '/SiteManagement',
    roles: ['super_admin', 'admin'],
    group: 'Sites',
    label: 'Site Management',
  },
  siteDetails: {
    name: 'SiteDetails',
    path: '/SiteDetails',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Sites',
    label: 'Site Details',
  },
  siteCheckInManagement: {
    name: 'SiteCheckInManagement',
    path: '/SiteCheckInManagement',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Sites',
    label: 'Check-In Management',
  },
  siteCheckIn: {
    name: 'SiteCheckIn',
    path: '/SiteCheckIn',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Sites',
    label: 'Site Check-In',
  },
  siteCheckInUser: {
    name: 'SiteCheckInUser',
    path: '/SiteCheckInUser',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Sites',
    label: 'Check-In User',
  },
  siteInspections: {
    name: 'SiteInspections',
    path: '/SiteInspections',
    roles: ['super_admin', 'admin', 'supervisor', 'officer'],
    group: 'Sites',
    label: 'Inspections',
  },
  siteInspectionForm: {
    name: 'SiteInspectionForm',
    path: '/SiteInspectionForm',
    roles: ['super_admin', 'admin', 'supervisor', 'officer'],
    group: 'Sites',
    label: 'Inspection Form',
  },
  siteQRManagement: {
    name: 'SiteQRManagement',
    path: '/SiteQRManagement',
    roles: ['super_admin', 'admin'],
    group: 'Sites',
    label: 'QR Management',
  },
  clientSiteMap: {
    name: 'ClientSiteMap',
    path: '/ClientSiteMap',
    roles: ['super_admin', 'client'],
    group: 'Sites',
    label: 'Site Map',
  },
  clientSiteSettings: {
    name: 'ClientSiteSettings',
    path: '/ClientSiteSettings',
    roles: ['super_admin', 'client'],
    group: 'Sites',
    label: 'Site Settings',
  },

  // Incidents & Security
  incidentForm: {
    name: 'IncidentForm',
    path: '/IncidentForm',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Incidents',
    label: 'Report Incident',
  },
  incidentFormAI: {
    name: 'IncidentFormAI',
    path: '/IncidentFormAI',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'Incidents',
    label: 'AI Incident Form',
  },
  incidentManagement: {
    name: 'IncidentManagement',
    path: '/IncidentManagement',
    roles: ['super_admin', 'admin'],
    group: 'Incidents',
    label: 'Incident Management',
  },
  incidentApproval: {
    name: 'IncidentApproval',
    path: '/IncidentApproval',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Incidents',
    label: 'Incident Approval',
  },
  incidentReports: {
    name: 'IncidentReports',
    path: '/IncidentReports',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Incidents',
    label: 'Incident Reports',
  },
  incidentAnalysis: {
    name: 'IncidentAnalysis',
    path: '/IncidentAnalysis',
    roles: ['super_admin', 'admin'],
    group: 'Incidents',
    label: 'Incident Analysis',
  },
  aiIncidentAnalysis: {
    name: 'AIIncidentAnalysis',
    path: '/AIIncidentAnalysis',
    roles: ['super_admin', 'admin'],
    group: 'Incidents',
    label: 'AI Analysis',
  },
  credentials: {
    name: 'Credentials',
    path: '/Credentials',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Security',
    label: 'Credentials',
  },
  credentialsDashboard: {
    name: 'CredentialsDashboard',
    path: '/CredentialsDashboard',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'Security',
    label: 'Credentials Dashboard',
  },
  credentialsManagement: {
    name: 'CredentialsManagement',
    path: '/CredentialsManagement',
    roles: ['super_admin', 'admin'],
    group: 'Security',
    label: 'Credentials Management',
  },
  stateLicensing: {
    name: 'StateLicensing',
    path: '/StateLicensing',
    roles: ['super_admin', 'admin'],
    group: 'Security',
    label: 'State Licensing',
  },

  // Training
  training: {
    name: 'Training',
    path: '/Training',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'Training',
    label: 'Training',
  },
  myTrainings: {
    name: 'MyTrainings',
    path: '/MyTrainings',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Training',
    label: 'My Training',
  },
  trainingAssignments: {
    name: 'TrainingAssignments',
    path: '/TrainingAssignments',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Training',
    label: 'Training Assignments',
  },
  trainingBuilder: {
    name: 'TrainingBuilder',
    path: '/TrainingBuilder',
    roles: ['super_admin', 'admin'],
    group: 'Training',
    label: 'Training Builder',
  },
  trainingLeaderboard: {
    name: 'TrainingLeaderboard',
    path: '/TrainingLeaderboard',
    roles: ['super_admin', 'admin'],
    group: 'Training',
    label: 'Leaderboard',
  },
  trainingSuggestions: {
    name: 'TrainingSuggestions',
    path: '/TrainingSuggestions',
    roles: ['super_admin', 'admin'],
    group: 'Training',
    label: 'Suggestions',
  },
  aiTrainingBuilder: {
    name: 'AITrainingBuilder',
    path: '/AITrainingBuilder',
    roles: ['super_admin', 'admin'],
    group: 'Training',
    label: 'AI Training Builder',
  },
  trainingGeneratorAI: {
    name: 'TrainingGeneratorAI',
    path: '/TrainingGeneratorAI',
    roles: ['super_admin', 'admin'],
    group: 'Training',
    label: 'AI Generator',
  },
  badgeManagement: {
    name: 'BadgeManagement',
    path: '/BadgeManagement',
    roles: ['super_admin', 'admin'],
    group: 'Training',
    label: 'Badge Management',
  },

  // Billing & Payroll
  invoices: {
    name: 'Invoices',
    path: '/Invoices',
    roles: ['super_admin', 'admin'],
    group: 'Billing',
    label: 'Invoices',
  },
  invoicesAdmin: {
    name: 'InvoicesAdmin',
    path: '/InvoicesAdmin',
    roles: ['super_admin', 'admin'],
    group: 'Billing',
    label: 'Invoices',
  },
  invoiceCreate: {
    name: 'InvoiceCreate',
    path: '/InvoiceCreate',
    roles: ['super_admin', 'admin'],
    group: 'Billing',
    label: 'Create Invoice',
  },
  invoiceDetail: {
    name: 'InvoiceDetail',
    path: '/InvoiceDetail',
    roles: ['super_admin', 'admin'],
    group: 'Billing',
    label: 'Invoice Detail',
  },
  invoiceSettings: {
    name: 'InvoiceSettings',
    path: '/InvoiceSettings',
    roles: ['super_admin', 'admin'],
    group: 'Billing',
    label: 'Invoice Settings',
  },
  clientInvoices: {
    name: 'ClientInvoices',
    path: '/ClientInvoices',
    roles: ['super_admin', 'client'],
    group: 'Billing',
    label: 'Invoices',
  },
  accountingDashboard: {
    name: 'AccountingDashboard',
    path: '/AccountingDashboard',
    roles: ['super_admin', 'admin'],
    group: 'Billing',
    label: 'Accounting Dashboard',
  },
  payroll: {
    name: 'Payroll',
    path: '/Payroll',
    roles: ['super_admin', 'admin'],
    group: 'Payroll',
    label: 'Payroll',
  },
  payrollIntegration: {
    name: 'PayrollIntegration',
    path: '/PayrollIntegration',
    roles: ['super_admin', 'admin'],
    group: 'Payroll',
    label: 'Payroll Integration',
  },
  payrollExport: {
    name: 'PayrollExport',
    path: '/PayrollExport',
    roles: ['super_admin', 'admin'],
    group: 'Payroll',
    label: 'Payroll Export',
  },
  taxForms: {
    name: 'TaxForms',
    path: '/TaxForms',
    roles: ['super_admin', 'admin'],
    group: 'Payroll',
    label: 'Tax Forms',
  },

  // Client Management
  clientManagement: {
    name: 'ClientManagement',
    path: '/ClientManagement',
    roles: ['super_admin', 'admin'],
    group: 'Clients',
    label: 'Client Management',
  },
  clientDetails: {
    name: 'ClientDetails',
    path: '/ClientDetails',
    roles: ['super_admin', 'admin'],
    group: 'Clients',
    label: 'Client Details',
  },
  clientOnboarding: {
    name: 'ClientOnboarding',
    path: '/ClientOnboarding',
    roles: ['super_admin', 'admin', 'client'],
    group: 'Clients',
    label: 'Onboarding',
  },
  clientProfile: {
    name: 'ClientProfile',
    path: '/ClientProfile',
    roles: ['super_admin', 'client'],
    group: 'Clients',
    label: 'Profile',
  },
  clientContracts: {
    name: 'ClientContracts',
    path: '/ClientContracts',
    roles: ['super_admin', 'admin', 'client'],
    group: 'Clients',
    label: 'Contracts',
  },
  clientSchedule: {
    name: 'ClientSchedule',
    path: '/ClientSchedule',
    roles: ['super_admin', 'client'],
    group: 'Clients',
    label: 'Schedule',
  },
  clientReports: {
    name: 'ClientReports',
    path: '/ClientReports',
    roles: ['super_admin', 'client'],
    group: 'Clients',
    label: 'Reports',
  },
  clientPatrolReports: {
    name: 'ClientPatrolReports',
    path: '/ClientPatrolReports',
    roles: ['super_admin', 'client'],
    group: 'Clients',
    label: 'Patrol Reports',
  },
  clientCommunicationHub: {
    name: 'ClientCommunicationHub',
    path: '/ClientCommunicationHub',
    roles: ['super_admin', 'admin', 'client'],
    group: 'Clients',
    label: 'Communication',
  },
  clientCredentials: {
    name: 'ClientCredentials',
    path: '/ClientCredentials',
    roles: ['super_admin', 'client'],
    group: 'Clients',
    label: 'Credentials',
  },
  clientFeedback: {
    name: 'ClientFeedback',
    path: '/ClientFeedback',
    roles: ['super_admin', 'client'],
    group: 'Clients',
    label: 'Feedback',
  },
  serviceRequests: {
    name: 'ServiceRequests',
    path: '/ServiceRequests',
    roles: ['super_admin', 'client'],
    group: 'Clients',
    label: 'Service Requests',
  },

  // Documents & Communication
  documentAdmin: {
    name: 'DocumentAdmin',
    path: '/DocumentAdmin',
    roles: ['super_admin', 'admin'],
    group: 'Documents',
    label: 'Document Admin',
  },
  documentLibrary: {
    name: 'DocumentLibrary',
    path: '/DocumentLibrary',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Documents',
    label: 'Document Library',
  },
  documents: {
    name: 'Documents',
    path: '/Documents',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Documents',
    label: 'Documents',
  },
  documentManagement: {
    name: 'DocumentManagement',
    path: '/DocumentManagement',
    roles: ['super_admin', 'admin'],
    group: 'Documents',
    label: 'Document Management',
  },
  onboardingDocuments: {
    name: 'OnboardingDocuments',
    path: '/OnboardingDocuments',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Onboarding',
    label: 'Onboarding Documents',
  },
  announcements: {
    name: 'Announcements',
    path: '/Announcements',
    roles: ['super_admin', 'admin', 'supervisor'],
    group: 'Communication',
    label: 'Announcements',
  },
  chat: {
    name: 'Chat',
    path: '/Chat',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'Communication',
    label: 'Chat',
  },
  policyManagement: {
    name: 'PolicyManagement',
    path: '/PolicyManagement',
    roles: ['super_admin', 'admin'],
    group: 'Documents',
    label: 'Policy Management',
  },

  // Reports & Analytics
  reports: {
    name: 'Reports',
    path: '/Reports',
    roles: ['super_admin', 'admin', 'supervisor', 'client'],
    group: 'Reports',
    label: 'Reports',
  },
  reportingDashboard: {
    name: 'ReportingDashboard',
    path: '/ReportingDashboard',
    roles: ['super_admin', 'admin'],
    group: 'Reports',
    label: 'Reporting',
  },
  reportAutomation: {
    name: 'ReportAutomation',
    path: '/ReportAutomation',
    roles: ['super_admin', 'admin'],
    group: 'Reports',
    label: 'Report Automation',
  },
  aiReports: {
    name: 'AIReports',
    path: '/AIReports',
    roles: ['super_admin', 'admin'],
    group: 'Reports',
    label: 'AI Reports',
  },
  aiReportsNew: {
    name: 'AIReportsNew',
    path: '/AIReportsNew',
    roles: ['super_admin', 'admin'],
    group: 'Reports',
    label: 'AI Reports New',
  },
  weeklySiteReports: {
    name: 'WeeklySiteReports',
    path: '/WeeklySiteReports',
    roles: ['super_admin', 'admin'],
    group: 'Reports',
    label: 'Weekly Site Reports',
  },
  ccwReciprocityMap: {
    name: 'CCWReciprocityMap',
    path: '/CCWReciprocityMap',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'Reports',
    label: 'CCW Reciprocity Map',
  },

  // Recognition
  recognitionSystem: {
    name: 'RecognitionSystem',
    path: '/RecognitionSystem',
    roles: ['super_admin', 'admin'],
    group: 'Recognition',
    label: 'Recognition System',
  },
  recognitionLeaderboard: {
    name: 'RecognitionLeaderboard',
    path: '/RecognitionLeaderboard',
    roles: ['super_admin', 'admin', 'employee', 'officer'],
    group: 'Recognition',
    label: 'Leaderboard',
  },
  performanceReviews: {
    name: 'PerformanceReviews',
    path: '/PerformanceReviews',
    roles: ['super_admin', 'admin'],
    group: 'People',
    label: 'Performance Reviews',
  },
  performanceReviewList: {
    name: 'PerformanceReviewList',
    path: '/PerformanceReviewList',
    roles: ['super_admin', 'admin'],
    group: 'People',
    label: 'Review List',
  },

  // System Settings
  settings: {
    name: 'Settings',
    path: '/Settings',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer', 'client'],
    group: 'Settings',
    label: 'Settings',
  },
  accessibility: {
    name: 'Accessibility',
    path: '/Accessibility',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer', 'client'],
    group: 'Settings',
    label: 'Accessibility',
  },
  companySettings: {
    name: 'CompanySettings',
    path: '/CompanySettings',
    roles: ['super_admin', 'admin'],
    group: 'Settings',
    label: 'Company Settings',
  },
  timekeepingSecuritySettings: {
    name: 'TimekeepingSecuritySettings',
    path: '/TimekeepingSecuritySettings',
    roles: ['super_admin', 'admin'],
    group: 'Settings',
    label: 'Timekeeping & Security',
  },
  rolesPermissions: {
    name: 'RolesPermissions',
    path: '/RolesPermissions',
    roles: ['super_admin', 'admin'],
    group: 'Settings',
    label: 'Roles & Permissions',
  },
  auditLog: {
    name: 'AuditLog',
    path: '/AuditLog',
    roles: ['super_admin', 'admin'],
    group: 'Settings',
    label: 'Audit Log',
  },
  dataImport: {
    name: 'DataImport',
    path: '/DataImport',
    roles: ['super_admin', 'admin'],
    group: 'Settings',
    label: 'Data Import',
  },

  // User Profile & Preferences
  profile: {
    name: 'Profile',
    path: '/Profile',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer', 'client'],
    group: 'Profile',
    label: 'Profile',
  },
  userPreferences: {
    name: 'UserPreferences',
    path: '/UserPreferences',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'Profile',
    label: 'Preferences',
  },
  notifications: {
    name: 'Notifications',
    path: '/Notifications',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer', 'client'],
    group: 'Profile',
    label: 'Notifications',
  },
  notificationPreferences: {
    name: 'NotificationPreferences',
    path: '/NotificationPreferences',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'Profile',
    label: 'Notification Preferences',
  },
  languageSettings: {
    name: 'LanguageSettings',
    path: '/LanguageSettings',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'Profile',
    label: 'Language',
  },

  // Miscellaneous
  onboarding: {
    name: 'Onboarding',
    path: '/Onboarding',
    roles: ['super_admin', 'admin'],
    group: 'People',
    label: 'Onboarding',
  },
  onboardingTask: {
    name: 'OnboardingTask',
    path: '/OnboardingTask',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'People',
    label: 'Onboarding Task',
  },
  employeeAvailabilitySettings: {
    name: 'EmployeeAvailabilitySettings',
    path: '/EmployeeAvailabilitySettings',
    roles: ['super_admin', 'employee', 'officer'],
    group: 'Operations',
    label: 'Availability Settings',
  },
  roleWorkspaceAdmin: {
    name: 'RoleWorkspaceAdmin',
    path: '/RoleWorkspaceAdmin',
    roles: ['super_admin', 'admin'],
    group: 'Settings',
    label: 'Role Workspace Admin',
  },
  roleWorkspaceView: {
    name: 'RoleWorkspaceView',
    path: '/RoleWorkspaceView',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer'],
    group: 'Settings',
    label: 'Role Workspace',
  },
  roleAudit: {
    name: 'RoleAudit',
    path: '/RoleAudit',
    roles: ['super_admin', 'admin', 'manager'],
    group: 'People',
    label: 'Role Audit',
  },
  certificateTemplates: {
    name: 'CertificateTemplates',
    path: '/CertificateTemplates',
    roles: ['super_admin', 'admin'],
    group: 'Training',
    label: 'Certificate Templates',
  },
  clientDashboard: {
    name: 'ClientDashboard',
    path: '/ClientDashboard',
    roles: ['super_admin', 'client'],
    group: 'Dashboard',
    label: 'Client Dashboard',
  },
  uniformInventory: {
    name: 'UniformInventory',
    path: '/UniformInventory',
    roles: ['super_admin', 'admin'],
    group: 'Operations',
    label: 'Uniform Inventory',
  },
  help: {
    name: 'Help',
    path: '/Help',
    roles: ['super_admin', 'admin', 'supervisor', 'employee', 'officer', 'client'],
    group: 'Support',
    label: 'Help',
  },

  // Previously missing pages
  employeeDashboard: {
    name: 'EmployeeDashboard',
    path: '/EmployeeDashboard',
    roles: ['super_admin', 'admin', 'employee', 'officer', 'manager'],
    group: 'Dashboard',
    label: 'Employee Dashboard',
  },
  adminDMMonitor: {
    name: 'AdminDMMonitor',
    path: '/AdminDMMonitor',
    roles: ['super_admin', 'admin', 'manager'],
    group: 'Communication',
    label: 'DM Monitor',
  },
  timesheetSummaryDashboard: {
    name: 'TimesheetSummaryDashboard',
    path: '/TimesheetSummaryDashboard',
    roles: ['super_admin', 'admin', 'supervisor', 'manager'],
    group: 'Operations',
    label: 'Timesheet Summary',
  },
  weeklySiteReports: {
    name: 'WeeklySiteReports',
    path: '/WeeklySiteReports',
    roles: ['super_admin', 'admin', 'manager'],
    group: 'Reports',
    label: 'Weekly Site Reports',
  },
  incidentSummaryReport: {
    name: 'IncidentSummaryReport',
    path: '/IncidentSummaryReport',
    roles: ['super_admin', 'admin', 'manager'],
    group: 'Incidents',
    label: 'Incident Summary Report',
  },
  serviceCoverageMap: {
    name: 'ServiceCoverageMap',
    path: '/ServiceCoverageMap',
    roles: ['super_admin', 'admin', 'manager'],
    group: 'Sites',
    label: 'Service Coverage Map',
  },
  stateLicensingSettings: {
    name: 'StateLicensingSettings',
    path: '/StateLicensingSettings',
    roles: ['super_admin', 'admin', 'manager'],
    group: 'Settings',
    label: 'State Licensing Settings',
  },
  employeeImportSettings: {
    name: 'EmployeeImportSettings',
    path: '/EmployeeImportSettings',
    roles: ['super_admin', 'admin', 'manager'],
    group: 'Settings',
    label: 'Employee Import Settings',
  },
  payrollSettings: {
    name: 'PayrollSettings',
    path: '/PayrollSettings',
    roles: ['super_admin', 'admin', 'manager'],
    group: 'Payroll',
    label: 'Payroll Settings',
  },
  archivedRecords: {
    name: 'ArchivedRecords',
    path: '/ArchivedRecords',
    roles: ['super_admin', 'admin', 'manager'],
    group: 'Settings',
    label: 'Archived Records',
  },
  aiReportsNew: {
    name: 'AIReportsNew',
    path: '/AIReportsNew',
    roles: ['super_admin', 'admin', 'manager'],
    group: 'Reports',
    label: 'AI Reports (New)',
  },
  monthlySiteReport: {
    name: 'MonthlySiteReport',
    path: '/MonthlySiteReport',
    roles: ['super_admin', 'admin', 'supervisor', 'manager'],
    group: 'Reports',
    label: 'Monthly Site Report',
  },
};

// Helper functions
export const getPagesByRole = (role) => {
  return Object.values(pagesConfig).filter(page => page.roles.includes(role));
};

export const getPagesByGroup = (role, group) => {
  return getPagesByRole(role).filter(page => page.group === group);
};

export const getAllGroups = (role) => {
  const pages = getPagesByRole(role);
  return [...new Set(pages.map(p => p.group))].sort();
};

export const getPageConfig = (pageName) => {
  return Object.values(pagesConfig).find(p => p.name === pageName);
};