// Static CCW state data — authoritative seed for all 50 states + DC
// honored_by_these_states = states that honor THIS state's permit
// honors_these_states = states THIS state honors

export const CCW_STATES = {
  AL: {
    state_code: "AL", state_name: "Alabama",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 19,
    permit_type: "shall-issue",
    honors_these_states: ["AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"],
    honored_by_these_states: ["AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: [],
    summary: "Alabama is a constitutional carry state. As of January 2023, no permit is required to carry a concealed handgun. Alabama issues permits for reciprocity purposes. Permits are issued by county sheriffs. Alabama honors all valid out-of-state permits.",
    self_defense_laws: "Stand Your Ground law. Castle Doctrine applies.",
    red_flag_law: false, permit_fee: "$20 annual", processing_time: "Immediate", training_required: "None required",
    last_updated: "2025-01-01", notes: "No permit needed. Permitless carry for anyone 19+.",
    official_source_url: "https://www.alea.gov/ccu"
  },
  AK: {
    state_code: "AK", state_name: "Alaska",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"],
    honored_by_these_states: ["AL","AZ","AR","FL","GA","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Alaska was the first constitutional carry state (2003). No permit required. Optional permit available for reciprocity. Alaska honors all valid out-of-state permits.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$88.25", processing_time: "30 days", training_required: "None required",
    last_updated: "2025-01-01", notes: "No permit required. Must be 21 to carry concealed.",
    official_source_url: "https://dps.alaska.gov/statewide/ccu"
  },
  AZ: {
    state_code: "AZ", state_name: "Arizona",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Arizona is a constitutional carry state since 2010. No permit required for anyone 21+. Arizona issues permits for reciprocity purposes and honors all valid out-of-state permits.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$60", processing_time: "75 days", training_required: "None required",
    last_updated: "2025-01-01", notes: "Permitless carry for 21+. Permit valid for 5 years.",
    official_source_url: "https://www.azdps.gov/services/public/concealed"
  },
  AR: {
    state_code: "AR", state_name: "Arkansas",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 18,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: [],
    summary: "Arkansas allows constitutional carry without a permit since 2018 for anyone 18+. Enhanced Carry permits offer additional rights. Arkansas honors all valid out-of-state permits.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$100", processing_time: "30 days", training_required: "8 hours",
    last_updated: "2025-01-01", notes: "No permit required for carry. Enhanced permit allows carry in additional locations.",
    official_source_url: "https://www.dfa.arkansas.gov/offices/regulatory-services/concealed-handgun-licensing/"
  },
  CA: {
    state_code: "CA", state_name: "California",
    permit_required: true, constitutional_carry: false, open_carry: false, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "California is a shall-issue state following NYSRPA v. Bruen. CCW permits are issued by county sheriffs or police chiefs. California does not honor any other state's permits and no states honor California permits.",
    self_defense_laws: "Castle Doctrine only. No statewide Stand Your Ground.", red_flag_law: true,
    permit_fee: "$20-$100 depending on county", processing_time: "90 days", training_required: "16 hours",
    last_updated: "2025-01-01", notes: "10-round magazine limit. Assault weapon restrictions. Safe storage laws.",
    official_source_url: "https://oag.ca.gov/firearms/ccw"
  },
  CO: {
    state_code: "CO", state_name: "Colorado",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","FL","GA","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","FL","GA","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: [],
    summary: "Colorado is a shall-issue state. Permits issued by county sheriffs. Colorado has a red flag law and some local jurisdictions have additional restrictions. Denver has stricter regulations.",
    self_defense_laws: "Stand Your Ground in some circumstances. Castle Doctrine.", red_flag_law: true,
    permit_fee: "$52.50", processing_time: "90 days", training_required: "Training course required",
    last_updated: "2025-01-01", notes: "15-round magazine limit. Denver has stricter laws.",
    official_source_url: "https://cbi.colorado.gov/sections/firearms-unit/concealed-handgun-permits"
  },
  CT: {
    state_code: "CT", state_name: "Connecticut",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "Connecticut is a shall-issue state but has very restrictive gun laws. Pistol permits required for both purchase and carry. Connecticut does not honor any other state's permits.",
    self_defense_laws: "Castle Doctrine. No statewide Stand Your Ground.", red_flag_law: true,
    permit_fee: "$35 state + $140 local", processing_time: "8 weeks", training_required: "NRA or equivalent course",
    last_updated: "2025-01-01", notes: "10-round magazine limit. Assault weapon restrictions.",
    official_source_url: "https://portal.ct.gov/DESPP/Division-of-State-Police/Special-Licensing-and-Firearms/Pistol-Permit"
  },
  DC: {
    state_code: "DC", state_name: "Washington D.C.",
    permit_required: true, constitutional_carry: false, open_carry: false, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "Washington D.C. has some of the strictest gun laws in the nation. No open carry permitted. Concealed carry permits are very difficult to obtain. D.C. honors no other jurisdiction's permits.",
    self_defense_laws: "Castle Doctrine only.", red_flag_law: true,
    permit_fee: "$75", processing_time: "90 days", training_required: "16 hours plus range",
    last_updated: "2025-01-01", notes: "Carrying in most public places prohibited. 10-round magazine limit.",
    official_source_url: "https://mpdc.dc.gov/service/concealed-pistol-license-application"
  },
  DE: {
    state_code: "DE", state_name: "Delaware",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "Delaware is a shall-issue state. Concealed carry licenses issued by prothonotary of Superior Court. Delaware does not honor any other state's permits.",
    self_defense_laws: "Castle Doctrine. No statewide Stand Your Ground.", red_flag_law: true,
    permit_fee: "$65", processing_time: "90 days", training_required: "Training course required",
    last_updated: "2025-01-01", notes: "17-round magazine limit proposed. Background checks for all sales.",
    official_source_url: "https://dsp.delaware.gov/permits/"
  },
  FL: {
    state_code: "FL", state_name: "Florida",
    permit_required: false, constitutional_carry: true, open_carry: false, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","GA","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Florida enacted constitutional carry in July 2023. No permit required for anyone 21+. Florida still issues permits for reciprocity. Florida does not allow open carry.",
    self_defense_laws: "Stand Your Ground law (statute 776.012). Castle Doctrine.", red_flag_law: true,
    permit_fee: "$97", processing_time: "90 days", training_required: "Training course required",
    last_updated: "2025-01-01", notes: "Open carry prohibited. Permit still useful for reciprocity.",
    official_source_url: "https://www.fdacs.gov/Licensing/Concealed-Weapon-or-Firearm-License"
  },
  GA: {
    state_code: "GA", state_name: "Georgia",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Georgia enacted constitutional carry (Carry Safe Act) in April 2023. No permit required for eligible residents 21+. Georgia Weapons Carry License still available for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$75", processing_time: "60 days", training_required: "None required",
    last_updated: "2025-01-01", notes: "Carry allowed in many previously restricted locations.",
    official_source_url: "https://dps.georgia.gov/georgia-weapons-carry-license"
  },
  HI: {
    state_code: "HI", state_name: "Hawaii",
    permit_required: true, constitutional_carry: false, open_carry: false, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "Hawaii is a shall-issue state following Bruen but with strict regulations. Permits extremely difficult to obtain in practice. Hawaii honors no other state's permits.",
    self_defense_laws: "Castle Doctrine only.", red_flag_law: true,
    permit_fee: "$10", processing_time: "Varies", training_required: "8 hours required",
    last_updated: "2025-01-01", notes: "Carry prohibited in many sensitive locations. Magazine restrictions.",
    official_source_url: "https://www.hawaii.gov/ag/firearms"
  },
  ID: {
    state_code: "ID", state_name: "Idaho",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 18,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: [],
    summary: "Idaho is a constitutional carry state. Permitless carry allowed statewide for Idaho residents 18+. Non-residents may carry with any valid permit. Idaho issues permits for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$20", processing_time: "30 days", training_required: "None required",
    last_updated: "2025-01-01", notes: "Enhanced permit requires training, honored by more states.",
    official_source_url: "https://www.isp.idaho.gov/permits/"
  },
  IL: {
    state_code: "IL", state_name: "Illinois",
    permit_required: true, constitutional_carry: false, open_carry: false, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "Illinois requires a Firearm Owner Identification Card (FOID) to possess firearms. A Concealed Carry License is required to carry. Illinois honors no other state's permits.",
    self_defense_laws: "Castle Doctrine. No statewide Stand Your Ground.", red_flag_law: true,
    permit_fee: "$150", processing_time: "90 days", training_required: "16 hours required",
    last_updated: "2025-01-01", notes: "FOID required to own firearms. CCL required to carry. Many prohibited locations.",
    official_source_url: "https://isp.illinois.gov/foid/concealed-carry"
  },
  IN: {
    state_code: "IN", state_name: "Indiana",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 18,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: [],
    summary: "Indiana enacted constitutional carry in July 2022. No permit required for anyone 18+ who may legally possess a firearm. Indiana still issues LTCH permits for reciprocity purposes.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "Free (formerly $125)", processing_time: "Immediate", training_required: "None required",
    last_updated: "2025-01-01", notes: "Permitless carry for 18+. LTCH still available for reciprocity.",
    official_source_url: "https://www.in.gov/isp/2376.htm"
  },
  IA: {
    state_code: "IA", state_name: "Iowa",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Iowa enacted constitutional carry in July 2021. No permit required for anyone 21+ who may legally possess a firearm. Iowa issues permits for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$50", processing_time: "30 days", training_required: "Training required for permit",
    last_updated: "2025-01-01", notes: "Permitless carry for 21+. Non-resident permits available.",
    official_source_url: "https://www.iowa.gov/permitstocary"
  },
  KS: {
    state_code: "KS", state_name: "Kansas",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Kansas enacted constitutional carry in July 2015. No permit required for state residents 21+. Kansas issues permits for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$32.50", processing_time: "45 days", training_required: "8 hours for permit",
    last_updated: "2025-01-01", notes: "Permitless carry for residents 21+.",
    official_source_url: "https://www.ag.ks.gov/licensing/concealed-carry"
  },
  KY: {
    state_code: "KY", state_name: "Kentucky",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Kentucky enacted constitutional carry in June 2019. No permit required for state residents 21+. Kentucky issues CCDW permits for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$60", processing_time: "60 days", training_required: "8 hours for permit",
    last_updated: "2025-01-01", notes: "Permitless carry for residents 21+.",
    official_source_url: "https://kentuckystatepolice.org/ccdw/"
  },
  LA: {
    state_code: "LA", state_name: "Louisiana",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 18,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Louisiana enacted constitutional carry in July 2024. No permit required. Louisiana issues permits for reciprocity. Permits require training.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$125", processing_time: "45 days", training_required: "8 hours for permit",
    last_updated: "2025-01-01", notes: "Permitless carry as of 2024.",
    official_source_url: "https://lsp.org/services.html"
  },
  ME: {
    state_code: "ME", state_name: "Maine",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Maine enacted constitutional carry in October 2015. No permit required for anyone 21+. Maine issues permits for reciprocity and they are widely honored.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: true,
    permit_fee: "$35", processing_time: "30 days", training_required: "None required",
    last_updated: "2025-01-01", notes: "Maine permit honored by many states including Maryland.",
    official_source_url: "https://www.maine.gov/dps/msp/licenses-permits/concealed-firearms-permits"
  },
  MD: {
    state_code: "MD", state_name: "Maryland",
    permit_required: true, constitutional_carry: false, open_carry: false, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: [],
    honored_by_these_states: ["AL","AR","ID","IN","MN","MT","NH","NC","ND","SD","VT"],
    restricted_reciprocity_states: ["AK","AZ","FL","GA","IA","KS","KY","LA","ME","MI","MS","MO","NE","OH","OK","SC","TN","TX","UT","VA","WV","WI","WY"],
    summary: "Maryland is a shall-issue state since NYSRPA v. Bruen on June 23rd 2022. Concealed weapons permits are issued by the Secretary of the Maryland State Police. Open carry is prohibited as of October 1, 2023. A Maryland Wear/Carry Handgun Permit (WCHP) is required for concealed carry. Minimum age 21 (general) or 18 (employment purposes only). Requires 16-hour state-approved firearms training course with live-fire component. Maryland does not honor permits from any other states.",
    self_defense_laws: "Castle Doctrine applies. No Stand Your Ground law.", red_flag_law: true,
    permit_fee: "$75 initial (rising to $125 after 10/01/23); $50 renewal (rising to $75)",
    processing_time: "90 days", training_required: "16 hours initial; 8 hours renewal",
    last_updated: "2025-01-01",
    notes: "Handgun Qualification License required to purchase handguns. 7-day waiting period. 10-round magazine limit. Assault Weapons Ban. Sensitive places where carry is prohibited.",
    official_source_url: "https://mdsp.maryland.gov/Organization/Pages/CriminalInvestigationBureau/LicensingDivision/Firearms/WearandCarryPermit.aspx"
  },
  MA: {
    state_code: "MA", state_name: "Massachusetts",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "may-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "Massachusetts is a may-issue state with very strict gun laws. LTC (License to Carry) required. Massachusetts does not honor any other state's permits.",
    self_defense_laws: "Castle Doctrine only. Duty to retreat.", red_flag_law: true,
    permit_fee: "$100", processing_time: "40 days", training_required: "Basic firearms safety course",
    last_updated: "2025-01-01", notes: "10-round magazine limit. Assault weapon restrictions. Extensive prohibited locations.",
    official_source_url: "https://www.mass.gov/how-to/apply-for-a-firearms-license"
  },
  MI: {
    state_code: "MI", state_name: "Michigan",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Michigan is a shall-issue state. Concealed Pistol Licenses issued by county clerks. Michigan has reciprocity with many states.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: true,
    permit_fee: "$100", processing_time: "45 days", training_required: "8 hours required",
    last_updated: "2025-01-01", notes: "No permit required for open carry. CPL required for concealed.",
    official_source_url: "https://www.michigan.gov/msp/divisions/ccu"
  },
  MN: {
    state_code: "MN", state_name: "Minnesota",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WI","WY"],
    restricted_reciprocity_states: [],
    summary: "Minnesota is a shall-issue state. Permits to Carry issued by county sheriffs. Minnesota honors many other state permits and is honored by many states including Maryland.",
    self_defense_laws: "Castle Doctrine. Limited Stand Your Ground.", red_flag_law: true,
    permit_fee: "$100", processing_time: "30 days", training_required: "Training course required",
    last_updated: "2025-01-01", notes: "No permit needed for open carry. Permit required for concealed.",
    official_source_url: "https://dps.mn.gov/divisions/bca/bca-divisions/administrative/Pages/permit-to-carry.aspx"
  },
  MS: {
    state_code: "MS", state_name: "Mississippi",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 18,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Mississippi allows constitutional carry. No permit required. Standard permit and Enhanced carry permit available for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$100", processing_time: "45 days", training_required: "None required (enhanced requires training)",
    last_updated: "2025-01-01", notes: "Enhanced permit allows carry in additional locations.",
    official_source_url: "https://www.dps.state.ms.us/firearms/"
  },
  MO: {
    state_code: "MO", state_name: "Missouri",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 19,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Missouri enacted constitutional carry in January 2017. No permit required for anyone 19+. Missouri issues permits for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$100", processing_time: "45 days", training_required: "8 hours for permit",
    last_updated: "2025-01-01", notes: "Permitless carry for 19+. Local preemption in place.",
    official_source_url: "https://ago.mo.gov/home/concealed-carry-permits"
  },
  MT: {
    state_code: "MT", state_name: "Montana",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 18,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: [],
    summary: "Montana allows constitutional carry statewide as of February 2021. No permit required. Permits still available for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$60", processing_time: "60 days", training_required: "None required",
    last_updated: "2025-01-01", notes: "Statewide permitless carry. Montana permit honored by many states including Maryland.",
    official_source_url: "https://dojmt.gov/enforcement/concealed-weapons-permits/"
  },
  NE: {
    state_code: "NE", state_name: "Nebraska",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Nebraska enacted constitutional carry in September 2023. No permit required for anyone 21+. Permits still available for reciprocity.",
    self_defense_laws: "Castle Doctrine. No Stand Your Ground statewide.", red_flag_law: false,
    permit_fee: "$100", processing_time: "45 days", training_required: "10 hours for permit",
    last_updated: "2025-01-01", notes: "New constitutional carry state as of 2023.",
    official_source_url: "https://statepatrol.nebraska.gov/concealed-handgun-permit"
  },
  NV: {
    state_code: "NV", state_name: "Nevada",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","ID","KS","KY","LA","ME","MI","MN","MS","MO","MT","NC","ND","OH","OK","SC","TN","TX","UT","VA","WV","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","ID","KS","KY","LA","ME","MI","MN","MS","MO","MT","NC","ND","OH","OK","SC","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: [],
    summary: "Nevada is a shall-issue state. Concealed Firearm Permits issued by county sheriffs. Nevada has limited reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: true,
    permit_fee: "$98.25", processing_time: "120 days", training_required: "Handgun safety course",
    last_updated: "2025-01-01", notes: "Universal background check required for all transfers.",
    official_source_url: "https://sheriffs.nv.gov/home/agencies/"
  },
  NH: {
    state_code: "NH", state_name: "New Hampshire",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 18,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: [],
    summary: "New Hampshire allows constitutional carry. No permit required. Pistol/Revolver License available for reciprocity. NH permit is honored by Maryland.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$10", processing_time: "14 days", training_required: "None required",
    last_updated: "2025-01-01", notes: "NH permit honored by Maryland and many other states.",
    official_source_url: "https://www.nh.gov/safety/divisions/nhsp/ssb/permitslicensing/chl.html"
  },
  NJ: {
    state_code: "NJ", state_name: "New Jersey",
    permit_required: true, constitutional_carry: false, open_carry: false, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "New Jersey is a shall-issue state following Bruen but with very restrictive regulations. Permits difficult to obtain in practice. No state honors NJ permits.",
    self_defense_laws: "Castle Doctrine only. Duty to retreat.", red_flag_law: true,
    permit_fee: "$200", processing_time: "90 days", training_required: "16 hours",
    last_updated: "2025-01-01", notes: "10-round magazine limit. Extensive sensitive places restrictions. No reciprocity.",
    official_source_url: "https://www.njsp.org/firearms/firearms-faqs.shtml"
  },
  NM: {
    state_code: "NM", state_name: "New Mexico",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AZ","CO","FL","MI","MO","VA","WY"],
    honored_by_these_states: ["AZ","CO","FL","MI","MO","VA","WY"],
    restricted_reciprocity_states: [],
    summary: "New Mexico is a shall-issue state. Concealed Handgun Licenses issued by Department of Public Safety. Limited reciprocity.",
    self_defense_laws: "Castle Doctrine. No statewide Stand Your Ground.", red_flag_law: true,
    permit_fee: "$100", processing_time: "30 days", training_required: "15 hours required",
    last_updated: "2025-01-01", notes: "Background check required for all private sales.",
    official_source_url: "https://www.dps.nm.gov/index.php/concealed-carry-unit/"
  },
  NY: {
    state_code: "NY", state_name: "New York",
    permit_required: true, constitutional_carry: false, open_carry: false, min_age: 21,
    permit_type: "may-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "New York is a shall-issue state following NYSRPA v. Bruen but has passed restrictive new laws (Concealed Carry Improvement Act). Permits issued by local licensing authorities. No reciprocity.",
    self_defense_laws: "Castle Doctrine. Duty to retreat outside home.", red_flag_law: true,
    permit_fee: "Varies by county ($10-$340)", processing_time: "6-8 months", training_required: "18 hours required",
    last_updated: "2025-01-01", notes: "Extensive sensitive places restrictions. Social media review required for applications.",
    official_source_url: "https://www.nyc.gov/site/nypd/services/law-enforcement/permits-licensing.page"
  },
  NC: {
    state_code: "NC", state_name: "North Carolina",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: [],
    summary: "North Carolina is a shall-issue state. Concealed Handgun Permits issued by county sheriffs. North Carolina has broad reciprocity and is honored by Maryland.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$90", processing_time: "45 days", training_required: "8 hours required",
    last_updated: "2025-01-01", notes: "Pistol purchase permit required for private sales. Permit honored by Maryland.",
    official_source_url: "https://www.ncdoj.gov/getting-a-concealed-carry-permit/"
  },
  ND: {
    state_code: "ND", state_name: "North Dakota",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 18,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: [],
    summary: "North Dakota allows constitutional carry for residents. Class 1 and Class 2 permits available for reciprocity. North Dakota permit is honored by Maryland.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$30", processing_time: "60 days", training_required: "8 hours for Class 1",
    last_updated: "2025-01-01", notes: "Class 1 permit requires training and is honored by more states.",
    official_source_url: "https://www.attorney general.nd.gov/concealed-weapons"
  },
  OH: {
    state_code: "OH", state_name: "Ohio",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Ohio enacted constitutional carry in June 2022. No permit required for anyone 21+. Ohio issues CHL permits for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$67", processing_time: "45 days", training_required: "8 hours for permit",
    last_updated: "2025-01-01", notes: "Permitless carry as of 2022. No duty to inform unless asked.",
    official_source_url: "https://www.ohioattorneygeneral.gov/Business/Services-for-Business/Concealed-Carry/Concealed-Carry-FAQs"
  },
  OK: {
    state_code: "OK", state_name: "Oklahoma",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Oklahoma enacted constitutional carry in November 2019. No permit required for anyone 21+ (18+ for active military). Oklahoma SDA permits available for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$100", processing_time: "60 days", training_required: "8 hours for permit",
    last_updated: "2025-01-01", notes: "Permitless carry for 21+.",
    official_source_url: "https://osbi.ok.gov/self-defense-act-licensing"
  },
  OR: {
    state_code: "OR", state_name: "Oregon",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "Oregon is a shall-issue state. Concealed Handgun Licenses issued by county sheriffs. Oregon does not honor any other state's permits.",
    self_defense_laws: "Castle Doctrine. No statewide Stand Your Ground.", red_flag_law: true,
    permit_fee: "$65", processing_time: "45 days", training_required: "Basic firearms safety",
    last_updated: "2025-01-01", notes: "10-round magazine limit. Measure 114 restrictions ongoing legal challenges.",
    official_source_url: "https://www.doj.state.or.us/oregon-department-of-justice/victims-services/firearms/"
  },
  PA: {
    state_code: "PA", state_name: "Pennsylvania",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: [],
    summary: "Pennsylvania is a shall-issue state. License to Carry Firearms issued by county sheriffs or chiefs of police in Philadelphia. Pennsylvania has reciprocity with many states but not Maryland.",
    self_defense_laws: "Stand Your Ground (Castle Doctrine Plus). No duty to retreat.", red_flag_law: false,
    permit_fee: "$20", processing_time: "45 days", training_required: "None required",
    last_updated: "2025-01-01", notes: "Philadelphia has additional restrictions. Philadelphia requires permit for open carry.",
    official_source_url: "https://www.psp.pa.gov/firearms/Pages/Firearms-Licensing.aspx"
  },
  RI: {
    state_code: "RI", state_name: "Rhode Island",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "may-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "Rhode Island is technically a shall-issue state but historically difficult to obtain permits. No reciprocity with other states.",
    self_defense_laws: "Castle Doctrine. Duty to retreat.", red_flag_law: false,
    permit_fee: "$40", processing_time: "90 days", training_required: "Safety course required",
    last_updated: "2025-01-01", notes: "Limited reciprocity. Attorney General issues some permits.",
    official_source_url: "https://riag.ri.gov/consumer-protection/bureau-criminal-identification/licenses-and-permits"
  },
  SC: {
    state_code: "SC", state_name: "South Carolina",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 18,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SD","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "South Carolina enacted constitutional carry (Open Carry with Training Act) in August 2023. No permit required. CWP still available for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$50", processing_time: "90 days", training_required: "8 hours for CWP",
    last_updated: "2025-01-01", notes: "Constitutional carry enacted 2023.",
    official_source_url: "https://sled.sc.gov/concealedweapon.aspx"
  },
  SD: {
    state_code: "SD", state_name: "South Dakota",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 18,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","TN","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","TN","TX","UT","VT","VA","WV","WI","WY"],
    restricted_reciprocity_states: [],
    summary: "South Dakota allows constitutional carry for anyone 18+ who can legally possess a firearm. Enhanced permits available. SD permit honored by Maryland.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$10", processing_time: "30 days", training_required: "None required",
    last_updated: "2025-01-01", notes: "SD permit honored by Maryland.",
    official_source_url: "https://dci.sd.gov/licensing/index.aspx"
  },
  TN: {
    state_code: "TN", state_name: "Tennessee",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 18,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TX","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Tennessee enacted constitutional carry in April 2021. No permit required for anyone 21+ (18+ for military). Tennessee HCP permits still available for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$100", processing_time: "90 days", training_required: "8 hours for permit",
    last_updated: "2025-01-01", notes: "Permitless carry for 21+.",
    official_source_url: "https://www.tn.gov/safety/driver-services/licenses/handgun-carry-permit.html"
  },
  TX: {
    state_code: "TX", state_name: "Texas",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","UT","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Texas enacted constitutional carry in September 2021. No permit required for anyone 21+ who can legally possess a firearm. Texas LTC permits still available for reciprocity.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine. Strong self-defense laws.", red_flag_law: false,
    permit_fee: "$40", processing_time: "60 days", training_required: "4-6 hours for LTC",
    last_updated: "2025-01-01", notes: "Permitless carry for 21+. LTC useful for reciprocity.",
    official_source_url: "https://www.dps.texas.gov/section/handgun-licensing"
  },
  UT: {
    state_code: "UT", state_name: "Utah",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","VT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Utah allows constitutional carry for anyone 21+. Utah BPC permits widely honored. Utah permit is accepted by Maryland (restricted).",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$40", processing_time: "60 days", training_required: "Firearms safety course",
    last_updated: "2025-01-01", notes: "Utah permit is one of the most widely honored permits in the US.",
    official_source_url: "https://bci.utah.gov/concealed-firearm/"
  },
  VT: {
    state_code: "VT", state_name: "Vermont",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 16,
    permit_type: "permitless",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WI","WY"],
    honored_by_these_states: ["AL","AR","ID","IN","MN","MT","NH","NC","ND","SD","MD"],
    restricted_reciprocity_states: [],
    summary: "Vermont has never required a permit for concealed or open carry (Vermont-style carry is the origin of constitutional carry). Vermont issues no permits but its residents' carry is honored by many states.",
    self_defense_laws: "Castle Doctrine only.", red_flag_law: true,
    permit_fee: "N/A - No permits issued", processing_time: "N/A", training_required: "None",
    last_updated: "2025-01-01", notes: "Vermont is the original constitutional carry state. Vermont permit honored by Maryland.",
    official_source_url: "https://ago.vermont.gov/bureau/civil/firearms.php"
  },
  VA: {
    state_code: "VA", state_name: "Virginia",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","WV","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Virginia is a shall-issue state. Concealed Handgun Permits issued by circuit courts. Virginia has broad reciprocity. Virginia permit is honored by Maryland.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine. No duty to retreat.", red_flag_law: true,
    permit_fee: "$50", processing_time: "45 days", training_required: "Safety course required",
    last_updated: "2025-01-01", notes: "Virginia permit honored by Maryland. No permit required on private property.",
    official_source_url: "https://www.vsp.virginia.gov/Firearms_CHP.shtm"
  },
  WA: {
    state_code: "WA", state_name: "Washington",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: [],
    honored_by_these_states: [],
    restricted_reciprocity_states: [],
    summary: "Washington is a shall-issue state. Concealed Pistol Licenses issued by local law enforcement. Washington does not honor any other state's permits.",
    self_defense_laws: "Castle Doctrine. No statewide Stand Your Ground.", red_flag_law: true,
    permit_fee: "$36", processing_time: "30 days", training_required: "None required",
    last_updated: "2025-01-01", notes: "10-round magazine limit effective 2024. High-capacity magazine ban.",
    official_source_url: "https://www.dol.wa.gov/business/firearms/concealed.html"
  },
  WV: {
    state_code: "WV", state_name: "West Virginia",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WI","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "West Virginia allows constitutional carry since May 2016. No permit required for anyone 21+. WV issues permits for reciprocity. WV permit is honored by Maryland.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$75", processing_time: "45 days", training_required: "8 hours for permit",
    last_updated: "2025-01-01", notes: "Permitless carry for 21+. WV permit honored by Maryland.",
    official_source_url: "https://www.wvsp.gov/about/Pages/LicensetoCarry.aspx"
  },
  WI: {
    state_code: "WI", state_name: "Wisconsin",
    permit_required: true, constitutional_carry: false, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WY"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WY"],
    restricted_reciprocity_states: ["MD"],
    summary: "Wisconsin is a shall-issue state. Concealed Carry Weapon licenses issued by Department of Justice. Wisconsin has broad reciprocity.",
    self_defense_laws: "Castle Doctrine. No duty to retreat in home.", red_flag_law: false,
    permit_fee: "$40", processing_time: "21 days", training_required: "Safety course required",
    last_updated: "2025-01-01", notes: "No permit needed for open carry. CCW permit required for concealed.",
    official_source_url: "https://www.doj.state.wi.us/dles/cib/concealedcarry"
  },
  WY: {
    state_code: "WY", state_name: "Wyoming",
    permit_required: false, constitutional_carry: true, open_carry: true, min_age: 21,
    permit_type: "shall-issue",
    honors_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VT","VA","WV","WI"],
    honored_by_these_states: ["AL","AK","AZ","AR","CO","FL","GA","ID","IN","IA","KS","KY","LA","ME","MD","MI","MN","MS","MO","MT","NE","NH","NC","ND","OH","OK","SC","SD","TN","TX","UT","VA","WV","WI"],
    restricted_reciprocity_states: ["MD"],
    summary: "Wyoming allows constitutional carry for residents 21+. Wyoming issues permits for reciprocity. WY permit honored by Maryland.",
    self_defense_laws: "Stand Your Ground. Castle Doctrine.", red_flag_law: false,
    permit_fee: "$56", processing_time: "60 days", training_required: "Firearms safety course",
    last_updated: "2025-01-01", notes: "Permitless carry for WY residents 21+.",
    official_source_url: "https://wss.wyo.gov/Concealed-Firearms"
  },
};